spring:
  servlet:
    multipart:
      max-file-size: 10MB       # Tama침o m치ximo por archivo
      max-request-size: 10MB    # Tama침o m치ximo total de la solicitud
  mail:
    host: smtp.gmail.com
    port: 456
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update 